### ISSUE TITLE
NPM dependency vulnerabilities

### ISSUE THREAD

**Issue by BrynkaIT** [gorguexo/page-count#1]
Hello @gorguexo ! Thank you for this package. It was just what we were looking for. One thing that we were hoping that you could address is updating some of the dependencies that have some known vulnerabilities.

xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
No fix available
node_modules/page-count/node_modules/xml2js
  page-count  *
  Depends on vulnerable versions of xml2js
  node_modules/page-count

Additionally, webpack seems to be a nested dependency and installs with the package. NPM audit returns the following:

glob-parent  <5.1.2
Severity: high
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/watchpack-chokidar2/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/watchpack-chokidar2/node_modules/chokidar
    watchpack-chokidar2  *
    Depends on vulnerable versions of chokidar
    node_modules/watchpack-chokidar2
      watchpack  1.7.2 - 1.7.5
      Depends on vulnerable versions of watchpack-chokidar2
      node_modules/watchpack
        webpack  4.39.0 - 5.1.0
        Depends on vulnerable versions of terser-webpack-plugin
        Depends on vulnerable versions of watchpack
        node_modules/webpack

Thank you!

**Comment by gorgueugr** [comment]
Hi @BrynkaIT,

Thanks for openning the issue,
I have upgraded the dependencies and replaced some of them. 

Hope you find it well.
