### ISSUE TITLE
Docx file page count not working

### ISSUE THREAD

**Issue by DharmikSondagar** [gorguexo/page-count#3]
The docx file count does not work properly. It throws 
/Project path/node_modules/xml2js/lib/parser.js:318
          return cb(null, result);
                 ^
TypeError: Cannot read properties of undefined (reading '0')
    at /Project path/node_modules/page-count/src/files-types/docx.count.ts:16:50
    
This type of error.

please help to take a look,
Thank You.

**Comment by gorgueugr** [comment]
Hi @DharmikSondagar,
could you give me more information about the docx file used?

Which program did you use to create the file? MS Office, Google Docs or other?

If you have a test file to replicate the error would be nice

Thank you

**Comment by DharmikSondagar** [comment]
[file-sample_100kB.docx](https://github.com/gorgueugr/page-count/files/13924198/file-sample_100kB.docx)
Hi @gorgueugr,
I've used this file. Can you please check it?

Thank You

**Comment by gorgueugr** [comment]
Unfortunately, certain docx files lack information about the number of pages in their properties.
The only way to acquire it the number of pages would be rendering the document to count the resultant pages. 

For the moment there is no easy solution without using external programs.

The easiest way would be converting the docx to pdf using libreoffice and then count the pdf pages.
This can be done with the libreoffice-convert package.

**Comment by DharmikSondagar** [comment]
Hi @gorgueugr,
Thank you for your support 🙌
